---
title: "Indicator Definitions"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 1
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

# Introduction
The Indicator Tracking Tool is a simple tool by users for users to inform supply chain decision-making process. The tool draws periodic and aggregated logistic data from the (KHIS, [https://hiskenya.org/](https://hiskenya.org/)) to help analyze and visualize supply chain performance focusing on family planning, immunization, TB and Malaria programs. Using tracer commodities, the tool explores several indicators including reporting rates, data quality, stock status, and stock outs for family planning. For immunization, the tool also analyzes and visualize coverage, and wastage. **Note ** that current year data will be updated daily, however if you have made changes to previous year's data in *KHIS* and would like to see the changes effected, please let us know. Below, we provide a detailed description on how the indicators presented are calculated.

# Reporting Rate

### Definition
This indicator measures the percentage of facilities that complete and submit reports according to the defined reporting schedule. 

### Purpose
This indicator measures the reporting levels and timeliness of key logistics information, including consumption and stock data for health facilities. The following questions can be answered by monitoring the performance of this indicator:

•	Is there information available for use by decision makers?

•	Is the information available in a timely manner for use by decision makers?

### Calculation
$$\text{Reporting Rate (%) } = \frac{\text{Number of facilities submitting the required report}}{\text{Total number of facilities that are expected to submit the report}} * 100$$

# Absolute Percentage Difference

### Definition
The ending balance of one month should match the beginning balance for the following month. This quality measure intends to directly compare any difference between recorded ending and beginning balances.  Discrepancies in these recorded balances can result in inaccurate ordering. 

### Purpose
It is critical to have accurate balances recorded.  The amount recorded at the end of a month should match the amount available at the beginning of the next month.  These data elements are used to make decisions about order quantities needed in order to avoid overstocking or understocking a product.

### Calculation
$$\text{APD (%) } = \frac{\text{Previous month Ending Balance} - \text{Beginning Balance this month}}{\text{Previous month Ending Balance}} * 100$$


# Months Of Stock

### Definition
This indicator measures the aggregated facility stock levels for tracer products by sub-county and county for each month, represented as months of stock. This can then be categorized within the established minimum and maximum stock level parameters. 
Facility minimum levels for FP is one month of stock while the maximum is 4 months of stock.

### Purpose
This indicator provides an overall measure of how counties and sub-counties are maintaining stock levels of products every month: are they adequately stocked, understocked or overstocked. This can help reveal whether the overall stock levels are adequate, insufficient, or overstocked and if redistribution is a possibility. If chronic overstocks exist, it identifies situations that could lead to product expiration and wastage. If low stock levels are present, it identifies situations that could result in stockouts or rationing. If this indicator is measured regularly, it can reveal patterns or facilities that are having ongoing difficulties maintaining adequate supply levels. It is also useful to look at it in conjunction with stockout rates to see if these can be predicted by stock levels, and if overstocks can be redistributed to avoid expiries and address stockouts or low stocks.  

### Calculation

First, we calculate the Average Monthly consumption (AMC) in the last 3 months} as follows

$$\text{AMC} = \frac{\text{Total consumption for the last 3 months}}{\text{3}}$$

We can then obtain the *Months Of Stock (MOS)* as shown below
$$\text{MOS} = \frac{\text{Ending Balance}}{\text{AMC}}$$

# Stock Out Rate

### Definition
This indicator measures the percentage of facilities that experienced a stock out of each of of products the site is expected to provide, at any point in the last month. Stockout rates are calculated by product across facilities. 


### Purpose
This indicator is a measure of product availability or absence over a period of time. It represents the overall ability of a facility or program to meet a client’s needs with a full range of products and services.  The following questions can be answered by monitoring the performance of this indicator using data from the FP dashboard:

•	What is the total percent of facilities stocked out of each product (by county and sub-county)?

•	Are certain sub-counties at greater risk of stockouts?  To what degree (less than or greater than 10%)?

•	Are certain products at greater risk of being stocked out? To what degree (less than or greater than 10%)?

### Calculation
$$\text{SOR (%) } = \frac{\text{Total number of facilities that reported zero ending balance}}{\text{Total numbe of facilities that provided the product in the last 12 months}} * 100$$

# Coverage

### Definition
Immunization coverage is the percentage of eligible fully-immunized infants compared to the total number of surviving infants in the target population

### Purpose
This indicator measures the use of services and serves as a proxy for full immunization access. It is an important measure of incremental progress in the county/sub county immunization program 

### Calculation
The immunization coverage rate is calculated by comparing the number of doses administered and the number in the target population of surviving infants under one year of age. 

$$\text{Coverage (%) } = \frac{\text{number of doses administered}}{\text{the number in the target population of surviving infants under one year of age}} * 100$$



# Wastage

### Definition
This indicator is defined as the percentage of stock for a given vaccine that was calculated to be wasted that month out of the total quantity of stock for that vaccine used that month

### Purpose
Reducing vaccine wastage rates helps reduce vaccine stock out rates and perhaps increase coverage. 

### Calculation
The immunization coverage rate is calculated by comparing the number of doses administered and the number in the target population of surviving infants under one year of age. 

$$\text{Wastage (%) } = \frac{\text{Quantity Used – Doses Administered}}{\text{Quantity Used}} * 100$$
$$\text{Where, Quantity used } = {\text{(Beginning Balance + Quantity Received) – Ending Balance}}$$





















